### ISSUE TITLE
Redesign the Thank You Page

### ISSUE THREAD

**Issue by Jayesh-JainX** [Jayesh-JainX/Hacktoberfest2023#25]
### Description:
Our current thank you page is a bit plain. Your task is to create a visually appealing and user-friendly redesign of our project's thank you page, making it a memorable experience for our supporters.

* Difficulty: beginner
* Estimated Time: 3-4 hours

**Comment by abc00xyz** [comment]
### Hi Jayesh,
Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.

Looking forward to your response. Thanks!

**Comment by Jayesh-JainX** [comment]
### Hello User,
Thank you for your interest in working on this issue. I've assigned the issue to you, and you can now start working on it. If you have any questions or need any assistance, feel free to ask. Good luck with your contribution!

Best regards,
[Jayesh](https://github.com/Jayesh-jainx)
