### ISSUE TITLE
Create a Time-Traveler's Dashboard

### ISSUE THREAD

**Issue by Jayesh-JainX** [Jayesh-JainX/Hacktoberfest2023#43]
### Description:
We're building a time-travel-themed project. Your task is to design a captivating dashboard that simulates time-travel controls and provides users with an immersive experience.

* Difficulty: intermediate
* Estimated Time: 6-7 hours

**Comment by abc00xyz** [comment]
### Hi Jayesh,
Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.

Looking forward to your response. Thanks!

**Comment by Jayesh-JainX** [comment]
### Hello User,
Thank you for your interest in working on this issue. I've assigned the issue to you, and you can now start working on it. If you have any questions or need any assistance, feel free to ask. Good luck with your contribution!

Best regards,
[Jayesh](https://github.com/Jayesh-jainx)
